### ISSUE TITLE
QM9 dataset

### ISSUE THREAD

**Issue by laixindev** [rmongeca/gnn#1]
hello，can you leak a address about QM9 dataset ？I want it like **_smilse_** format but it seems ** xyz** online

thank you ！

**Comment by ghost** [comment]
You can take a look at the [QM9 Dataset Jupyter Notebook](https://github.com/rmongeca/gnn-qm9/blob/master/QM9%20Dataset.ipynb) for an example on how to use the .xyz files information to build the graphs.

In particular, you can see in the process_files function how I extract and handle the SMILES of each molecule. Hope it helps!

> Note: please take into account that this repository is still a work in progress and thus there may be unstable functionalities in the pushed notebooks.
